# Generated by Django 6.0.4 on 2026-08-11 07:16

import django.db.models.deletion
import invitaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboracion', '0001_initial'),
        ('proveedores', '0009_financial_semantics_k831'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('CLIENTE_PLANNER', 'Cliente / Planner'), ('PLANNER_PROVEEDOR', 'Planner / Proveedor'), ('INTERNO', 'Interno empresa / Planner')], max_length=30)),
                ('activa', models.BooleanField(default=True)),
                ('archivada_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_servicio_creadas', to=settings.AUTH_USER_MODEL)),
                ('servicio_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_workspace', to='proveedores.servicioevento')),
            ],
            options={
                'ordering': ['servicio_evento', 'canal'],
            },
        ),
        migrations.CreateModel(
            name='MensajeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MENSAJE', 'Mensaje'), ('SISTEMA', 'Sistema')], default='MENSAJE', max_length=15)),
                ('texto', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('editado_en', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_servicio_workspace', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='colaboracion.conversacionservicio')),
            ],
            options={
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdjuntoMensajeServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='colaboracion/workspace/adjuntos/', validators=[invitaciones.models.validar_documento])),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=120)),
                ('tamano_bytes', models.PositiveBigIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='colaboracion.mensajeservicio')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TemaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas_servicio_creados', to=settings.AUTH_USER_MODEL)),
                ('servicio_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_workspace', to='proveedores.servicioevento')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REFERENCIA', 'Referencia'), ('INSPIRACION', 'Inspiracion'), ('DOCUMENTO', 'Documento'), ('COMPROBANTE', 'Comprobante'), ('OTRO', 'Otro')], default='REFERENCIA', max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('adjunto_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_generadas', to='colaboracion.adjuntomensajeservicio')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_servicio_creadas', to=settings.AUTH_USER_MODEL)),
                ('mensaje_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_generadas', to='colaboracion.mensajeservicio')),
                ('servicio_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias_workspace', to='proveedores.servicioevento')),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias', to='colaboracion.temaservicio')),
            ],
            options={
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
        migrations.AddField(
            model_name='mensajeservicio',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='colaboracion.temaservicio'),
        ),
        migrations.AddIndex(
            model_name='conversacionservicio',
            index=models.Index(fields=['servicio_evento', 'canal', 'activa'], name='colab_conv_srv_canal_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversacionservicio',
            constraint=models.UniqueConstraint(fields=('servicio_evento', 'canal'), name='colab_conversacion_servicio_canal_unico'),
        ),
        migrations.AddIndex(
            model_name='temaservicio',
            index=models.Index(fields=['servicio_evento', 'activo'], name='colab_tema_srv_act_idx'),
        ),
        migrations.AddConstraint(
            model_name='temaservicio',
            constraint=models.UniqueConstraint(fields=('servicio_evento', 'nombre'), name='colab_tema_servicio_nombre_unico'),
        ),
        migrations.AddIndex(
            model_name='referenciaservicio',
            index=models.Index(fields=['servicio_evento', 'tipo'], name='colab_ref_srv_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeservicio',
            index=models.Index(fields=['conversacion', 'fecha'], name='colab_msg_conv_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeservicio',
            index=models.Index(fields=['tema', 'fecha'], name='colab_msg_tema_fecha_idx'),
        ),
    ]
