# Generated by Django 6.0.4 on 2026-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoBoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novio', models.CharField(max_length=100)),
                ('novia', models.CharField(max_length=100)),
                ('fecha_evento', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('mensaje_principal', models.TextField()),
                ('dress_code', models.CharField(blank=True, max_length=150, null=True)),
                ('link_mapa', models.URLField(blank=True, null=True)),
                ('link_whatsapp', models.URLField(blank=True, null=True)),
                ('imagen_portada', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
