# Generated by Django 6.0.4 on 2026-04-09 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0002_eventoboda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoboda',
            old_name='fecha_evento',
            new_name='fecha_fiesta',
        ),
        migrations.RenameField(
            model_name='eventoboda',
            old_name='lugar',
            new_name='lugar_fiesta',
        ),
        migrations.RenameField(
            model_name='eventoboda',
            old_name='mensaje_principal',
            new_name='mensaje_general',
        ),
        migrations.RemoveField(
            model_name='eventoboda',
            name='direccion',
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='fecha_misa',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='frase_portada',
            field=models.CharField(default='Nos encantara su prensencia', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='lugar_misa',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
