# Generated by Django 6.0.4 on 2026-04-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0003_rename_fecha_evento_eventoboda_fecha_fiesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoinvitacion',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
