# Generated by Django 6.0.4 on 2026-04-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0004_grupoinvitacion_telefono_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoinvitacion',
            name='estado_envio',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('INVITACION_PREPARADA', 'Invitación preparada'), ('RECORDATORIO_PREPARADO', 'Recordatorio preparado')], default='PENDIENTE', max_length=30),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='fecha_ultimo_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='fecha_ultimo_recordatorio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
