# Generated by Django 6.0.4 on 2026-07-22 02:20

import django.db.models.deletion
from django.db import migrations, models


def asociar_grupos_a_evento(apps, schema_editor):
    EventoBoda = apps.get_model('invitaciones', 'EventoBoda')
    GrupoInvitacion = apps.get_model('invitaciones', 'Grupoinvitacion')

    evento = EventoBoda.objects.first()
    if not evento:
        return

    for grupo in GrupoInvitacion.objects.filter(evento__isnull=True):
        grupo.evento_id = evento.id
        if grupo.tipo == 'PERSONAL':
            grupo.cantidad_extra_permitida = max((grupo.cantidad_maxima or 1) - 1, 0)
        grupo.save(update_fields=['evento', 'cantidad_extra_permitida'])


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0006_grupo_respuesta_unica'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoboda',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='cancion',
            field=models.FileField(blank=True, null=True, upload_to='canciones/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='color_acento',
            field=models.CharField(default='#d2b074', max_length=20),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='color_principal',
            field=models.CharField(default='#2f7a4d', max_length=20),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='color_secundario',
            field=models.CharField(default='#63b96d', max_length=20),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='foto_portada',
            field=models.FileField(blank=True, null=True, upload_to='portadas/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='link_mesa_regalos',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='mostrar_album',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='mostrar_mapa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='mostrar_menu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='mostrar_regalos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='acompanantes_adultos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='acompanantes_ninos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='cantidad_extra_permitida',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='invitaciones.eventoboda'),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='mesa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(asociar_grupos_a_evento, migrations.RunPython.noop),
        migrations.CreateModel(
            name='EnlaceRegalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('visible', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalos', to='invitaciones.eventoboda')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.FileField(upload_to='album/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='invitaciones.eventoboda')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_persona', models.CharField(choices=[('ADULTO', 'Adulto'), ('NINO', 'Niño')], default='ADULTO', max_length=10)),
                ('asistira', models.BooleanField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('mesa', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='invitaciones.grupoinvitacion')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuBoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('ADULTO', 'Adulto'), ('NINO', 'Niño'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('visible', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='invitaciones.eventoboda')),
            ],
        ),
    ]
