# Generated by Django 6.0.4 on 2026-07-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0007_eventoboda_activo_eventoboda_cancion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoboda',
            name='estilo_letra',
            field=models.CharField(choices=[('CLASICA', 'Clásica elegante'), ('EDITORIAL', 'Editorial sofisticada'), ('MODERNA', 'Moderna limpia'), ('ROMANTICA', 'Romántica manuscrita')], default='CLASICA', max_length=20),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='link_mapa_fiesta',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='link_mapa_misa',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='paleta_colores',
            field=models.CharField(choices=[('BOSQUE', 'Verde bosque y dorado'), ('ROSA', 'Rosa romántico'), ('TERRACOTA', 'Terracota elegante'), ('AZUL', 'Azul noche'), ('LAVANDA', 'Lavanda suave'), ('DORADO', 'Champagne dorado'), ('PERSONALIZADA', 'Personalizada con códigos')], default='BOSQUE', max_length=20),
        ),
    ]
