# Generated by Django 6.0.4 on 2026-07-22 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0008_eventoboda_estilo_letra_eventoboda_link_mapa_fiesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoboda',
            name='dress_code_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='dress_code_imagen',
            field=models.FileField(blank=True, null=True, upload_to='dress_code/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='mapa_fiesta_embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='mapa_misa_embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='mostrar_padres_padrinos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='texto_detalles',
            field=models.TextField(default='Aquí tienes ceremonia, fiesta, ubicación y dress code en un solo lugar.'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='texto_invitacion',
            field=models.TextField(default='Hemos reservado este espacio para celebrar juntos este día tan especial.'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='texto_rsvp',
            field=models.TextField(default='Tu respuesta nos ayuda a organizar lugares, mesas y buffet.'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='titulo_album',
            field=models.CharField(default='Álbum', max_length=120),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='titulo_cuenta_regresiva',
            field=models.CharField(default='Faltan', max_length=120),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='titulo_detalles',
            field=models.CharField(default='Detalles del evento', max_length=120),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='titulo_invitacion',
            field=models.CharField(default='Tu invitación', max_length=120),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='titulo_menu',
            field=models.CharField(default='Menú', max_length=120),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='titulo_padres_padrinos',
            field=models.CharField(default='Con la bendición de', max_length=120),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='titulo_regalos',
            field=models.CharField(default='Regalos', max_length=120),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='titulo_rsvp',
            field=models.CharField(default='Confirma tu asistencia', max_length=120),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='estilo_letra',
            field=models.CharField(choices=[('CLASICA', 'Clásica elegante'), ('EDITORIAL', 'Editorial sofisticada'), ('MODERNA', 'Moderna limpia'), ('ROMANTICA', 'Romántica manuscrita'), ('MANUSCRITA', 'Manuscrita fina')], default='CLASICA', max_length=20),
        ),
        migrations.CreateModel(
            name='ColorDressCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('color', models.CharField(default='#ffffff', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colores_dress_code', to='invitaciones.eventoboda')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PersonaCeremonia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('PADRES_NOVIO', 'Padres del novio'), ('PADRES_NOVIA', 'Padres de la novia'), ('PADRINOS', 'Padrinos')], max_length=20)),
                ('etiqueta', models.CharField(default='Papá', max_length=80)),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas_ceremonia', to='invitaciones.eventoboda')),
            ],
            options={
                'ordering': ['seccion', 'orden', 'id'],
            },
        ),
    ]
