# Generated by Django 6.0.4 on 2026-07-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0009_eventoboda_dress_code_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoboda',
            name='orden_album',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='orden_cuenta_regresiva',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='orden_detalles',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='orden_invitacion',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='orden_menu',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='orden_padres_padrinos',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='orden_regalos',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='orden_rsvp',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
