# Generated by Django 6.0.4 on 2026-07-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0010_eventoboda_orden_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoboda',
            name='fondo_album',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='fondo_cuenta_regresiva',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='fondo_detalles',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='fondo_invitacion',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='fondo_menu',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='fondo_padres_padrinos',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='fondo_regalos',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='fondo_rsvp',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/'),
        ),
    ]
