# Generated by Django 6.0.4 on 2026-07-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0011_eventoboda_fondo_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoboda',
            name='dress_code_imagen',
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='dress_code_permitido_imagen',
            field=models.FileField(blank=True, null=True, upload_to='dress_code/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='dress_code_prohibido_imagen',
            field=models.FileField(blank=True, null=True, upload_to='dress_code/'),
        ),
        migrations.DeleteModel(
            name='ColorDressCode',
        ),
    ]
