# Generated by Django 6.0.4 on 2026-07-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0012_remove_eventoboda_dress_code_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoboda',
            name='fondo_padres_padrinos',
        ),
        migrations.RemoveField(
            model_name='eventoboda',
            name='mostrar_padres_padrinos',
        ),
        migrations.RemoveField(
            model_name='eventoboda',
            name='orden_padres_padrinos',
        ),
        migrations.RemoveField(
            model_name='eventoboda',
            name='titulo_padres_padrinos',
        ),
    ]
