# Generated by Django 5.2.12 on 2026-07-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0013_remove_eventoboda_fondo_padres_padrinos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoboda',
            name='logo_portada',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='monograma_sobre',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='paleta_sobre',
            field=models.CharField(choices=[('BOSQUE', 'Verde bosque y dorado'), ('ROSA', 'Rosa romántico'), ('TERRACOTA', 'Terracota elegante'), ('AZUL', 'Azul noche'), ('LAVANDA', 'Lavanda suave'), ('DORADO', 'Champagne dorado'), ('TINTA_MARFIL', 'Tinta azul y marfil'), ('NEGRO_DORADO', 'Negro y dorado'), ('VINO_ROSA', 'Vino y rosa empolvado'), ('SALVIA_PERLA', 'Salvia y perla'), ('PERSONALIZADA', 'Personalizada con códigos')], default='TINTA_MARFIL', max_length=20),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='sello_sobre',
            field=models.FileField(blank=True, null=True, upload_to='sellos/'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='texto_boton_sobre',
            field=models.CharField(default='Abrir invitación', max_length=80),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='paleta_colores',
            field=models.CharField(choices=[('BOSQUE', 'Verde bosque y dorado'), ('ROSA', 'Rosa romántico'), ('TERRACOTA', 'Terracota elegante'), ('AZUL', 'Azul noche'), ('LAVANDA', 'Lavanda suave'), ('DORADO', 'Champagne dorado'), ('TINTA_MARFIL', 'Tinta azul y marfil'), ('NEGRO_DORADO', 'Negro y dorado'), ('VINO_ROSA', 'Vino y rosa empolvado'), ('SALVIA_PERLA', 'Salvia y perla'), ('PERSONALIZADA', 'Personalizada con códigos')], default='BOSQUE', max_length=20),
        ),
    ]
