# Generated by Django 5.2.12 on 2026-07-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0014_eventoboda_logo_portada_eventoboda_monograma_sobre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoboda',
            name='estilo_letra',
            field=models.CharField(choices=[('CLASICA', 'Clásica elegante'), ('EDITORIAL', 'Editorial sofisticada'), ('MODERNA', 'Moderna limpia'), ('ROMANTICA', 'Romántica manuscrita'), ('MANUSCRITA', 'Manuscrita fina'), ('CURSIVA_ELEGANTE', 'Cursiva elegante')], default='CLASICA', max_length=20),
        ),
    ]
