# Generated by Django 5.2.12 on 2026-07-23 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0015_alter_eventoboda_estilo_letra'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlaceregalo',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enlaceregalo',
            name='clabe',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='enlaceregalo',
            name='instrucciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enlaceregalo',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='enlaceregalo',
            name='tipo',
            field=models.CharField(choices=[('TIENDA', 'Link de tienda'), ('DEPOSITO', 'Deposito bancario')], default='TIENDA', max_length=20),
        ),
        migrations.AddField(
            model_name='enlaceregalo',
            name='titular',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='enlaceregalo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ItinerarioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=180, null=True)),
                ('icono', models.CharField(choices=[('ceremonia', 'Ceremonia'), ('civil', 'Civil'), ('recepcion', 'Recepcion'), ('brindis', 'Brindis'), ('cena', 'Cena'), ('baile', 'Baile'), ('general', 'General')], default='general', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerario', to='invitaciones.eventoboda')),
            ],
            options={
                'ordering': ['orden', 'hora', 'id'],
            },
        ),
    ]
