# Generated by Django 5.2.12 on 2026-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0016_enlaceregalo_banco_enlaceregalo_clabe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoboda',
            name='link_album_compartido',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='mostrar_album_compartido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='texto_album_compartido',
            field=models.TextField(default='Ayúdanos a guardar tus mejores momentos. Sube tus fotos y videos al álbum compartido.'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='titulo_album_compartido',
            field=models.CharField(default='Comparte tus fotos', max_length=120),
        ),
    ]
