# Generated by Django 5.2.12 on 2026-07-23 16:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0017_eventoboda_link_album_compartido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoboda',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='eventos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='direccion_ceremonia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='direccion_recepcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='estado',
            field=models.CharField(choices=[('PLANEACION', 'Planeacion'), ('PREPARACION', 'En preparacion'), ('CONFIRMADO', 'Confirmado'), ('EN_CURSO', 'En curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PLANEACION', max_length=20),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='etiqueta_principal',
            field=models.CharField(default='Novia', max_length=80),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='etiqueta_secundario',
            field=models.CharField(default='Novio', max_length=80),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='mostrar_nombre_secundario',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='nombre_evento',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='nombre_principal',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='nombre_secundario',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='numero_invitados_estimado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='presupuesto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='tema',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='tipo_evento',
            field=models.CharField(choices=[('BODA', 'Boda'), ('XV', 'XV anos'), ('BABY_SHOWER', 'Baby shower'), ('BAUTIZO', 'Bautizo'), ('CUMPLEANOS', 'Cumpleanos'), ('ANIVERSARIO', 'Aniversario'), ('CORPORATIVO', 'Corporativo'), ('OTRO', 'Otro')], default='BODA', max_length=20),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='wedding_planner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_planeados', to=settings.AUTH_USER_MODEL),
        ),
    ]
