# Generated by Django 6.0.4 on 2026-07-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0019_crear_roles_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoinvitacion',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='requiere_menu_infantil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grupoinvitacion',
            name='restricciones_alimentarias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='apellidos',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='menu_infantil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitado',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='restricciones_alimentarias',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
