# Generated by Django 6.0.4 on 2026-07-23 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoboda',
            name='capacidad_contratada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='organizaciones.empresasuscriptora'),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='precio_por_persona',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='organizaciones.sedeevento'),
        ),
    ]
