# Generated by Django 5.2.12 on 2026-07-23 19:48

import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0021_eventoboda_capacidad_contratada_eventoboda_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoboda',
            name='cancion',
            field=models.FileField(blank=True, null=True, upload_to='canciones/', validators=[invitaciones.models.validar_audio]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='dress_code_permitido_imagen',
            field=models.FileField(blank=True, null=True, upload_to='dress_code/', validators=[invitaciones.models.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='dress_code_prohibido_imagen',
            field=models.FileField(blank=True, null=True, upload_to='dress_code/', validators=[invitaciones.models.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='fondo_album',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/', validators=[invitaciones.models.validar_media_visual]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='fondo_cuenta_regresiva',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/', validators=[invitaciones.models.validar_media_visual]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='fondo_detalles',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/', validators=[invitaciones.models.validar_media_visual]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='fondo_invitacion',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/', validators=[invitaciones.models.validar_media_visual]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='fondo_menu',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/', validators=[invitaciones.models.validar_media_visual]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='fondo_regalos',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/', validators=[invitaciones.models.validar_media_visual]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='fondo_rsvp',
            field=models.FileField(blank=True, null=True, upload_to='fondos_secciones/', validators=[invitaciones.models.validar_media_visual]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='foto_portada',
            field=models.FileField(blank=True, null=True, upload_to='portadas/', validators=[invitaciones.models.validar_media_visual]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='logo_portada',
            field=models.FileField(blank=True, null=True, upload_to='logos/', validators=[invitaciones.models.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='eventoboda',
            name='sello_sobre',
            field=models.FileField(blank=True, null=True, upload_to='sellos/', validators=[invitaciones.models.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='fotoevento',
            name='imagen',
            field=models.FileField(upload_to='album/', validators=[invitaciones.models.validar_media_visual]),
        ),
    ]
