# Generated by Django 5.2.12 on 2026-07-27 21:45

import django.db.models.deletion
import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0022_alter_eventoboda_cancion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_evento', models.CharField(choices=[('BODA', 'Boda'), ('XV', 'XV anos'), ('BABY_SHOWER', 'Baby shower'), ('BAUTIZO', 'Bautizo'), ('CUMPLEANOS', 'Cumpleanos'), ('ANIVERSARIO', 'Aniversario'), ('CORPORATIVO', 'Corporativo'), ('OTRO', 'Otro')], default='BODA', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('paleta_colores', models.CharField(choices=[('BOSQUE', 'Verde bosque y dorado'), ('ROSA', 'Rosa romántico'), ('TERRACOTA', 'Terracota elegante'), ('AZUL', 'Azul noche'), ('LAVANDA', 'Lavanda suave'), ('DORADO', 'Champagne dorado'), ('TINTA_MARFIL', 'Tinta azul y marfil'), ('NEGRO_DORADO', 'Negro y dorado'), ('VINO_ROSA', 'Vino y rosa empolvado'), ('SALVIA_PERLA', 'Salvia y perla'), ('PERSONALIZADA', 'Personalizada con códigos')], default='BOSQUE', max_length=20)),
                ('paleta_sobre', models.CharField(choices=[('BOSQUE', 'Verde bosque y dorado'), ('ROSA', 'Rosa romántico'), ('TERRACOTA', 'Terracota elegante'), ('AZUL', 'Azul noche'), ('LAVANDA', 'Lavanda suave'), ('DORADO', 'Champagne dorado'), ('TINTA_MARFIL', 'Tinta azul y marfil'), ('NEGRO_DORADO', 'Negro y dorado'), ('VINO_ROSA', 'Vino y rosa empolvado'), ('SALVIA_PERLA', 'Salvia y perla'), ('PERSONALIZADA', 'Personalizada con códigos')], default='TINTA_MARFIL', max_length=20)),
                ('estilo_letra', models.CharField(choices=[('CLASICA', 'Clásica elegante'), ('EDITORIAL', 'Editorial sofisticada'), ('MODERNA', 'Moderna limpia'), ('ROMANTICA', 'Romántica manuscrita'), ('MANUSCRITA', 'Manuscrita fina'), ('CURSIVA_ELEGANTE', 'Cursiva elegante')], default='CLASICA', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('configuracion', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de invitacion',
                'verbose_name_plural': 'Plantillas de invitacion',
                'ordering': ['tipo_evento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SeccionInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PORTADA', 'Portada'), ('PADRES_PADRINOS', 'Padres y padrinos'), ('CUENTA_REGRESIVA', 'Cuenta regresiva'), ('DETALLES', 'Detalles, mapas y dress code'), ('ITINERARIO', 'Itinerario'), ('ALBUM', 'Album'), ('MENU', 'Menu'), ('REGALOS', 'Regalos'), ('ALBUM_COMPARTIDO', 'Album compartido'), ('RSVP', 'Confirmacion'), ('PERSONALIZADA', 'Personalizada')], max_length=30)),
                ('titulo', models.CharField(blank=True, max_length=140, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('mostrar_titulo_texto', models.BooleanField(default=True)),
                ('imagen_titulo', models.FileField(blank=True, null=True, upload_to='secciones/titulos/', validators=[invitaciones.models.validar_media_visual])),
                ('fondo', models.FileField(blank=True, null=True, upload_to='secciones/fondos/', validators=[invitaciones.models.validar_media_visual])),
                ('posicion_fondo', models.CharField(choices=[('center center', 'Centro'), ('top center', 'Arriba'), ('bottom center', 'Abajo'), ('center left', 'Izquierda'), ('center right', 'Derecha')], default='center center', max_length=30)),
                ('opacidad_fondo', models.DecimalField(decimal_places=2, default=0.18, max_digits=3)),
                ('color_texto', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones_invitacion', to='invitaciones.eventoboda')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones_evento', to='invitaciones.plantillainvitacion')),
            ],
            options={
                'verbose_name': 'Seccion de invitacion',
                'verbose_name_plural': 'Secciones de invitacion',
                'ordering': ['evento', 'orden', 'id'],
                'unique_together': {('evento', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='MediaSeccionInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='secciones/media/', validators=[invitaciones.models.validar_media_visual])),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medios', to='invitaciones.seccioninvitacion')),
            ],
            options={
                'verbose_name': 'Media de seccion',
                'verbose_name_plural': 'Media de secciones',
                'ordering': ['seccion', 'orden', 'id'],
            },
        ),
    ]
