# Generated by Django 5.2.12 on 2026-07-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0023_plantillainvitacion_seccioninvitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccioninvitacion',
            name='tipo',
            field=models.CharField(choices=[('PORTADA', 'Portada'), ('PADRES_PADRINOS', 'Padres y padrinos'), ('CUENTA_REGRESIVA', 'Cuenta regresiva'), ('DETALLES', 'Detalles y mapas'), ('DRESS_CODE', 'Dress code'), ('ITINERARIO', 'Itinerario'), ('ALBUM', 'Album'), ('MENU', 'Menu'), ('REGALOS', 'Regalos'), ('ALBUM_COMPARTIDO', 'Album compartido'), ('RSVP', 'Confirmacion'), ('PERSONALIZADA', 'Personalizada')], max_length=30),
        ),
    ]
