# Generated by Django 5.2.12 on 2026-07-27 22:20

import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0024_alter_seccioninvitacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoboda',
            name='foto_ceremonia',
            field=models.FileField(blank=True, null=True, upload_to='lugares/', validators=[invitaciones.models.validar_media_visual]),
        ),
        migrations.AddField(
            model_name='eventoboda',
            name='foto_recepcion',
            field=models.FileField(blank=True, null=True, upload_to='lugares/', validators=[invitaciones.models.validar_media_visual]),
        ),
    ]
