# Generated by Django 5.2.12 on 2026-07-28 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0025_eventoboda_foto_ceremonia_eventoboda_foto_recepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProduccionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_contrato', models.CharField(blank=True, max_length=80, null=True)),
                ('cliente_contrato', models.CharField(blank=True, max_length=180, null=True)),
                ('arrendador', models.CharField(blank=True, max_length=180, null=True)),
                ('lugar_contrato', models.CharField(blank=True, max_length=180, null=True)),
                ('adultos_contratados', models.PositiveIntegerField(default=0)),
                ('ninos_contratados', models.PositiveIntegerField(default=0)),
                ('horas_evento', models.PositiveIntegerField(default=0)),
                ('recepcion_hora', models.TimeField(blank=True, null=True)),
                ('inicio_evento', models.TimeField(blank=True, null=True)),
                ('fin_evento', models.TimeField(blank=True, null=True)),
                ('minutos_desalojo', models.PositiveIntegerField(default=0)),
                ('costo_hora_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_renta_salon', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposito_apartado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anticipo_recibido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_antes_liquidacion', models.PositiveIntegerField(default=0)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_cuenta', models.CharField(blank=True, max_length=80, null=True)),
                ('clabe', models.CharField(blank=True, max_length=40, null=True)),
                ('tarjeta', models.CharField(blank=True, max_length=80, null=True)),
                ('color_mantel', models.CharField(blank=True, max_length=120, null=True)),
                ('color_servilleta', models.CharField(blank=True, max_length=120, null=True)),
                ('tipo_mesa', models.CharField(blank=True, max_length=160, null=True)),
                ('tamano_mesa', models.CharField(blank=True, max_length=120, null=True)),
                ('mobiliario', models.TextField(blank=True, null=True)),
                ('tipo_loza_cristaleria', models.TextField(blank=True, null=True)),
                ('diseno_carpa', models.CharField(blank=True, max_length=180, null=True)),
                ('tamano_carpa', models.CharField(blank=True, max_length=120, null=True)),
                ('color_carpa', models.CharField(blank=True, max_length=120, null=True)),
                ('montaje_carpa', models.TextField(blank=True, null=True)),
                ('menu_entrada', models.TextField(blank=True, null=True)),
                ('menu_plato_fuerte', models.TextField(blank=True, null=True)),
                ('menu_postre', models.TextField(blank=True, null=True)),
                ('menu_trasnochado', models.TextField(blank=True, null=True)),
                ('menu_infantil', models.TextField(blank=True, null=True)),
                ('bebidas', models.TextField(blank=True, null=True)),
                ('servicios_incluidos', models.TextField(blank=True, null=True)),
                ('notas_puntualidad', models.TextField(blank=True, null=True)),
                ('politica_cancelacion', models.TextField(blank=True, null=True)),
                ('notas_contrato', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_produccion', to='invitaciones.eventoboda')),
            ],
            options={
                'verbose_name': 'Detalle de produccion del evento',
                'verbose_name_plural': 'Detalles de produccion de eventos',
            },
        ),
    ]
