# Generated by Django 5.2.12 on 2026-07-28 05:57

import django.db.models.deletion
import invitaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0026_detalleproduccionevento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FONDO', 'Fondo'), ('PORTADA', 'Portada'), ('TITULO', 'Titulo visual'), ('DECORACION', 'Decoracion'), ('ALBUM', 'Album'), ('VIDEO', 'Video'), ('GIF', 'GIF')], default='DECORACION', max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('archivo', models.FileField(upload_to='editor_invitaciones/assets/', validators=[invitaciones.models.validar_media_visual])),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_invitacion_subidos', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets_invitacion', to='invitaciones.eventoboda')),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_editor', to='invitaciones.seccioninvitacion')),
            ],
            options={
                'verbose_name': 'Asset de invitacion',
                'verbose_name_plural': 'Assets de invitacion',
                'ordering': ['evento', 'orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DisenoInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Diseño principal', max_length=120)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=20)),
                ('configuracion_borrador', models.JSONField(blank=True, default=dict)),
                ('configuracion_publicada', models.JSONField(blank=True, default=dict)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disenos_invitacion_actualizados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diseno_visual', to='invitaciones.eventoboda')),
                ('plantilla_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disenos_evento', to='invitaciones.plantillainvitacion')),
            ],
            options={
                'verbose_name': 'Diseño visual de invitacion',
                'verbose_name_plural': 'Diseños visuales de invitacion',
            },
        ),
        migrations.CreateModel(
            name='VersionDisenoInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('configuracion', models.JSONField(default=dict)),
                ('publicado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_diseno_invitacion', to=settings.AUTH_USER_MODEL)),
                ('diseno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='invitaciones.disenoinvitacion')),
            ],
            options={
                'verbose_name': 'Version de diseño de invitacion',
                'verbose_name_plural': 'Versiones de diseño de invitacion',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
    ]
