# Generated by Django 5.2.12 on 2026-07-30 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0027_assetinvitacion_disenoinvitacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteInvitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEN', 'Imagen'), ('BOTON', 'Boton')], max_length=20)),
                ('x', models.FloatField(default=50)),
                ('y', models.FloatField(default=50)),
                ('width', models.FloatField(default=44)),
                ('height', models.FloatField(default=12)),
                ('rotation', models.FloatField(default=0)),
                ('opacity', models.FloatField(default=1)),
                ('z_index', models.PositiveIntegerField(default=20)),
                ('locked', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_invitacion', to='invitaciones.eventoboda')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='invitaciones.seccioninvitacion')),
            ],
            options={
                'verbose_name': 'Componente de invitacion',
                'verbose_name_plural': 'Componentes de invitacion',
                'ordering': ['evento', 'seccion', 'z_index', 'id'],
                'indexes': [models.Index(fields=['evento', 'seccion', 'tipo'], name='invitacione_evento__44a6f5_idx'), models.Index(fields=['evento', 'hidden'], name='invitacione_evento__42ed05_idx')],
            },
        ),
    ]
