# Generated by Django 6.0.4 on 2026-08-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0030_builder_document_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinvitacion',
            name='tipo',
            field=models.CharField(choices=[('FONDO', 'Fondo'), ('PORTADA', 'Portada'), ('TITULO', 'Titulo visual'), ('DECORACION', 'Decoracion'), ('ALBUM', 'Album'), ('VIDEO', 'Video'), ('GIF', 'GIF'), ('AUDIO', 'Audio')], default='DECORACION', max_length=20),
        ),
    ]
