# Generated by Django 6.0.4 on 2026-08-20 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0034_eventoboda_generic_domain_k9r2a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RsvpConfiguracionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=12)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('recordatorio_desde', models.DateTimeField(blank=True, null=True)),
                ('mostrar_recordatorio', models.BooleanField(default=True)),
                ('mensaje_abierto', models.CharField(blank=True, default='Confirma tu asistencia antes de la fecha indicada.', max_length=220)),
                ('mensaje_recordatorio', models.CharField(blank=True, default='La fecha límite para confirmar está próxima.', max_length=220)),
                ('mensaje_cerrado', models.CharField(blank=True, default='El periodo de confirmación ha finalizado. Si necesitas hacer un cambio, comunícate con los anfitriones.', max_length=220)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvp_eventos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_configuracion', to='invitaciones.eventoboda')),
            ],
            options={
                'verbose_name': 'Configuración RSVP del evento',
                'verbose_name_plural': 'Configuraciones RSVP del evento',
            },
        ),
        migrations.CreateModel(
            name='RsvpExcepcionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('HEREDA', 'Hereda del evento'), ('HABILITADA', 'Habilitada manualmente'), ('BLOQUEADA', 'Bloqueada')], default='HEREDA', max_length=14)),
                ('motivo', models.CharField(blank=True, default='', max_length=220)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvp_grupos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_excepcion', to='invitaciones.grupoinvitacion')),
            ],
            options={
                'verbose_name': 'Excepción RSVP de invitación',
                'verbose_name_plural': 'Excepciones RSVP de invitación',
            },
        ),
    ]
