export const COMPONENTS_MODULE_NAME = "components";
export const COMPONENT_CONTRACT_VERSION = 1;

export const COMPONENT_CAPABILITIES = Object.freeze({
    CONTAINER: "CONTAINER",
    AUTO_LAYOUT: "AUTO_LAYOUT",
    CONSTRAINTS: "CONSTRAINTS",
    TRANSFORM: "TRANSFORM",
    MEDIA: "MEDIA",
    ACTIONABLE: "ACTIONABLE",
    DYNAMIC_DATA: "DYNAMIC_DATA",
    COMPOSITE: "COMPOSITE",
});

export const BUILTIN_COMPONENT_TYPES = Object.freeze({
    TEXT: "TEXT",
    IMAGE: "IMAGE",
    BUTTON: "BUTTON",
    CARD: "CARD",
    CONTAINER: "CONTAINER",
    MAP: "MAP",
    VIDEO: "VIDEO",
    RSVP: "RSVP",
    COUNTDOWN: "COUNTDOWN",
    ICON: "ICON",
    SEPARATOR: "SEPARATOR",
});
