# Generated by Django 6.0.4 on 2026-08-17 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_backfill_participantes_legacy'),
        ('invitaciones', '0033_repair_component_layout_columns'),
        ('paquetes', '0005_alter_propuestaevento_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoevento',
            name='propuesta_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_v2', to='paquetes.propuestaevento'),
        ),
        migrations.AddField(
            model_name='contratoevento',
            name='snapshot_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contratoevento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('FIRMADO', 'Firmado'), ('CONTRATADO', 'Contratado'), ('CANCELADO', 'Cancelado'), ('REEMPLAZADO', 'Reemplazado')], default='BORRADOR', max_length=20),
        ),
        migrations.AddIndex(
            model_name='contratoevento',
            index=models.Index(fields=['snapshot_version'], name='evt_contrato_snap_ver_idx'),
        ),
        migrations.AddConstraint(
            model_name='contratoevento',
            constraint=models.UniqueConstraint(fields=('propuesta_origen',), name='eventos_contrato_propuesta_origen_unica'),
        ),
    ]
