# Generated by Django 6.0.4 on 2026-08-18 00:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_contratoevento_propuesta_origen_and_more'),
        ('invitaciones', '0033_repair_component_layout_columns'),
        ('paquetes', '0005_alter_propuestaevento_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoevento',
            name='materializacion_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contratoevento',
            name='materializado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contratoevento',
            index=models.Index(fields=['materializacion_version'], name='evt_contrato_mat_ver_idx'),
        ),
    ]
