# Generated by Django 6.0.4 on 2026-07-23 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSuscriptora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=160)),
                ('razon_social', models.CharField(blank=True, max_length=180, null=True)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('contacto_nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('plan', models.CharField(choices=[('BASICO', 'Basico'), ('PROFESIONAL', 'Profesional'), ('ENTERPRISE', 'Enterprise')], default='PROFESIONAL', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('max_eventos_activos', models.PositiveIntegerField(default=20)),
                ('max_usuarios', models.PositiveIntegerField(default=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa suscriptora',
                'verbose_name_plural': 'Empresas suscriptoras',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='MembresiaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN_EMPRESA', 'Administrador de empresa'), ('WEDDING_PLANNER', 'Wedding planner'), ('VENTAS', 'Ventas'), ('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor')], max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('puede_gestionar_catalogos', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='organizaciones.empresasuscriptora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresia de empresa',
                'verbose_name_plural': 'Membresias de empresa',
                'ordering': ['empresa', 'rol', 'usuario__username'],
                'unique_together': {('empresa', 'usuario', 'rol')},
            },
        ),
        migrations.CreateModel(
            name='SedeEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('tipo', models.CharField(choices=[('SALON', 'Salon'), ('JARDIN', 'Jardin'), ('TERRAZA', 'Terraza'), ('HACIENDA', 'Hacienda'), ('OTRO', 'Otro')], default='SALON', max_length=20)),
                ('capacidad_minima', models.PositiveIntegerField(default=0)),
                ('capacidad_maxima', models.PositiveIntegerField(default=0)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='organizaciones.empresasuscriptora')),
            ],
            options={
                'verbose_name': 'Sede del evento',
                'verbose_name_plural': 'Sedes del evento',
                'ordering': ['empresa', 'nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
    ]
