# Generated by Django 5.2.12 on 2026-07-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresasuscriptora',
            name='colores_marca',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='empresasuscriptora',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresasuscriptora',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('BLOQUEADA', 'Bloqueada'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20),
        ),
        migrations.AddField(
            model_name='empresasuscriptora',
            name='logotipo',
            field=models.FileField(blank=True, null=True, upload_to='empresas/logotipos/'),
        ),
        migrations.AddField(
            model_name='empresasuscriptora',
            name='rfc',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
