# Generated by Django 6.0.4 on 2026-07-23 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('INFO', 'Informacion'), ('ALERTA', 'Alerta'), ('PAGO', 'Pago'), ('TAREA', 'Tarea'), ('PROVEEDOR', 'Proveedor'), ('INVITADOS', 'Invitados'), ('DOCUMENTO', 'Documento'), ('APROBACION', 'Aprobacion')], default='INFO', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('enlace', models.CharField(blank=True, max_length=255, null=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_evento', to='invitaciones.eventoboda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['leida', '-fecha_creacion'],
            },
        ),
    ]
