# Generated by Django 6.0.4 on 2026-08-14 04:56

import django.db.models.deletion
import catalogo.storage
import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0002_empresasuscriptora_colores_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('categoria', models.CharField(choices=[('BANQUETE', 'Banquete'), ('BEBIDAS', 'Bebidas'), ('DECORACION', 'Decoracion'), ('MOBILIARIO', 'Mobiliario'), ('MUSICA', 'Musica'), ('AUDIO_ILUMINACION', 'Audio e iluminacion'), ('FOTOGRAFIA_VIDEO', 'Fotografia y video'), ('PERSONAL', 'Personal'), ('LOGISTICA', 'Logistica'), ('INVITACIONES', 'Invitaciones'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(choices=[('EVENTO', 'Evento'), ('PERSONA', 'Persona'), ('ADULTO', 'Adulto'), ('NINO', 'Nino'), ('HORA', 'Hora'), ('UNIDAD', 'Unidad'), ('MESA', 'Mesa'), ('PAQUETE', 'Paquete'), ('OTRO', 'Otro')], default='EVENTO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('imagen_principal', models.FileField(blank=True, null=True, storage=catalogo.storage.PrivateCatalogoStorage(), upload_to='catalogo/servicios/imagenes/', validators=[invitaciones.models.validar_imagen])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_catalogo', to='organizaciones.empresasuscriptora')),
            ],
            options={
                'verbose_name': 'Servicio de catalogo',
                'verbose_name_plural': 'Servicios de catalogo',
                'ordering': ['empresa', 'categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioCatalogoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMAGEN', 'Imagen'), ('PDF', 'PDF')], max_length=10)),
                ('archivo', models.FileField(storage=catalogo.storage.PrivateCatalogoStorage(), upload_to='catalogo/servicios/archivos/')),
                ('titulo', models.CharField(blank=True, max_length=140, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='catalogo.serviciocatalogo')),
            ],
            options={
                'verbose_name': 'Archivo de servicio de catalogo',
                'verbose_name_plural': 'Archivos de servicios de catalogo',
                'ordering': ['servicio', 'orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='serviciocatalogo',
            index=models.Index(fields=['empresa', 'activo'], name='cat_serv_emp_act_idx'),
        ),
        migrations.AddIndex(
            model_name='serviciocatalogo',
            index=models.Index(fields=['empresa', 'categoria'], name='cat_serv_emp_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviciocatalogo',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='catalogo_servicio_empresa_nombre_unico'),
        ),
        migrations.AddIndex(
            model_name='serviciocatalogoarchivo',
            index=models.Index(fields=['servicio', 'tipo'], name='cat_arch_srv_tipo_idx'),
        ),
    ]
