# Generated by Django 6.0.4 on 2026-08-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('proveedores', '0009_financial_semantics_k831'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorServicioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios_catalogo_k9', to='proveedores.proveedor')),
                ('servicio_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedores_servicio_catalogo', to='catalogo.serviciocatalogo')),
            ],
            options={
                'verbose_name': 'Servicio ofrecido por proveedor',
                'verbose_name_plural': 'Servicios ofrecidos por proveedor',
                'ordering': ['proveedor', 'servicio_catalogo__nombre'],
                'indexes': [models.Index(fields=['proveedor', 'activo'], name='cat_prov_srv_prov_act_idx'), models.Index(fields=['servicio_catalogo', 'activo'], name='cat_prov_srv_cat_act_idx')],
                'constraints': [models.UniqueConstraint(fields=('proveedor', 'servicio_catalogo'), name='cat_prov_servicio_catalogo_unico')],
            },
        ),
    ]
