# Generated by Django 6.0.4 on 2026-07-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CONTRATO', 'Contrato'), ('COTIZACION', 'Cotizacion'), ('COMPROBANTE', 'Comprobante de pago'), ('FACTURA', 'Factura'), ('MENU', 'Menu'), ('FOTOGRAFIA', 'Fotografia'), ('DISENO', 'Diseno'), ('PLANO', 'Plano'), ('LISTA', 'Lista'), ('IDENTIFICACION', 'Identificacion'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('titulo', models.CharField(max_length=160)),
                ('archivo', models.FileField(upload_to='documentos/eventos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('visible_cliente', models.BooleanField(default=False)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_cargados', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_evento', to='invitaciones.eventoboda')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_evento', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Documento del evento',
                'verbose_name_plural': 'Documentos del evento',
                'ordering': ['evento', '-fecha_carga'],
            },
        ),
    ]
