# Generated by Django 5.2.12 on 2026-07-23 19:48

import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoevento',
            name='archivo',
            field=models.FileField(upload_to='documentos/eventos/', validators=[invitaciones.models.validar_documento]),
        ),
    ]
