# Generated by Django 6.0.4 on 2026-07-23 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de gasto',
                'verbose_name_plural': 'Categorias de gasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GastoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=160)),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcialmente pagado'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='presupuesto.categoriagasto')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_evento', to='invitaciones.eventoboda')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_evento', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Gasto del evento',
                'verbose_name_plural': 'Gastos del evento',
                'ordering': ['evento', 'fecha_limite', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='PagoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Deposito'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=120, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='presupuesto/comprobantes/')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='presupuesto.gastoevento')),
            ],
            options={
                'verbose_name': 'Pago del evento',
                'verbose_name_plural': 'Pagos del evento',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
    ]
