# Generated by Django 6.0.4 on 2026-07-23 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('EN_REVISION', 'En revision'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('porcentaje_avance', models.PositiveIntegerField(default=0)),
                ('categoria', models.CharField(choices=[('GENERAL', 'General'), ('INVITADOS', 'Invitados'), ('PROVEEDORES', 'Proveedores'), ('CATERING', 'Catering'), ('DECORACION', 'Decoracion'), ('MUSICA', 'Musica'), ('MESAS', 'Mesas'), ('PRESUPUESTO', 'Presupuesto'), ('DOCUMENTOS', 'Documentos'), ('OTRA', 'Otra')], default='GENERAL', max_length=20)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='tareas/evidencias/')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_evento', to='invitaciones.eventoboda')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea del evento',
                'verbose_name_plural': 'Tareas del evento',
                'ordering': ['evento', 'fecha_limite', 'prioridad', 'titulo'],
            },
        ),
    ]
