# Generated by Django 5.2.12 on 2026-07-23 19:49

import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareaevento',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='tareas/evidencias/', validators=[invitaciones.models.validar_documento]),
        ),
    ]
