# Generated by Django 6.0.4 on 2026-07-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntretenimientoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DJ', 'DJ'), ('BANDA', 'Banda'), ('MARIACHI', 'Mariachi'), ('GRUPO', 'Grupo musical'), ('SOLISTA', 'Solista'), ('MUSICA_AMBIENTAL', 'Musica ambiental'), ('ANIMACION', 'Animacion'), ('OTRO', 'Otro')], default='DJ', max_length=30)),
                ('nombre_artista', models.CharField(max_length=140)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('duracion', models.CharField(blank=True, max_length=80, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('requerimientos_tecnicos', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROPUESTO', 'Propuesto'), ('COTIZADO', 'Cotizado'), ('APROBADO', 'Aprobado'), ('CONTRATADO', 'Contratado'), ('ANTICIPO_PAGADO', 'Anticipo pagado'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='PROPUESTO', max_length=30)),
                ('notas', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretenimiento_evento', to='invitaciones.eventoboda')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretenimientos', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Entretenimiento del evento',
                'verbose_name_plural': 'Entretenimiento del evento',
                'ordering': ['evento', 'hora_inicio', 'nombre_artista'],
            },
        ),
        migrations.CreateModel(
            name='CancionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_momento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('CEREMONIA', 'Ceremonia'), ('PRIMER_BAILE', 'Primer baile'), ('PADRES', 'Baile con padres'), ('CENA', 'Cena'), ('RAMO', 'Lanzamiento de ramo'), ('PASTEL', 'Pastel'), ('FIESTA', 'Fiesta'), ('PROHIBIDA', 'Cancion prohibida'), ('OTRO', 'Otro')], default='FIESTA', max_length=30)),
                ('nombre_cancion', models.CharField(max_length=160)),
                ('artista', models.CharField(blank=True, max_length=140, null=True)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canciones_evento', to='invitaciones.eventoboda')),
                ('entretenimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canciones', to='entretenimiento.entretenimientoevento')),
            ],
            options={
                'verbose_name': 'Cancion del evento',
                'verbose_name_plural': 'Canciones del evento',
                'ordering': ['evento', 'orden', 'tipo_momento', 'nombre_cancion'],
            },
        ),
    ]
