# Generated by Django 6.0.4 on 2026-07-23 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadItinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('PROVEEDORES', 'Llegada de proveedores'), ('MONTAJE', 'Montaje'), ('MAQUILLAJE', 'Maquillaje'), ('PEINADO', 'Peinado'), ('FOTO_VIDEO', 'Foto y video'), ('CEREMONIA', 'Ceremonia'), ('TRASLADO', 'Traslado'), ('RECEPCION', 'Recepcion'), ('CENA', 'Cena'), ('BRINDIS', 'Brindis'), ('BAILE', 'Baile'), ('PASTEL', 'Pastel'), ('DESMONTAJE', 'Desmontaje'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=180, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('RETRASADA', 'Retrasada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_itinerario', to='invitaciones.eventoboda')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_itinerario', to='proveedores.proveedor')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de itinerario',
                'verbose_name_plural': 'Actividades de itinerario',
                'ordering': ['evento', 'fecha', 'hora_inicio', 'orden'],
            },
        ),
    ]
