# Generated by Django 6.0.4 on 2026-07-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de alimento',
                'verbose_name_plural': 'Categorias de alimentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vegetariano', models.BooleanField(default=False)),
                ('vegano', models.BooleanField(default=False)),
                ('sin_gluten', models.BooleanField(default=False)),
                ('contiene_alergenos', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alimentos', to='catering.categoriaalimento')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimentos',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteBuffet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('personas_incluidas', models.PositiveIntegerField(default=0)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_por_persona_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_por_nino', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paquetes_buffet', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Paquete de buffet',
                'verbose_name_plural': 'Paquetes de buffet',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CateringEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_adultos', models.PositiveIntegerField(default=0)),
                ('cantidad_ninos', models.PositiveIntegerField(default=0)),
                ('cantidad_proveedores', models.PositiveIntegerField(default=0)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_degustacion', models.DateField(blank=True, null=True)),
                ('hora_servicio', models.TimeField(blank=True, null=True)),
                ('horario_montaje', models.TimeField(blank=True, null=True)),
                ('duracion_servicio', models.CharField(blank=True, max_length=80, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alimentos_seleccionados', models.ManyToManyField(blank=True, related_name='eventos_catering', to='catering.alimento')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_evento', to='invitaciones.eventoboda')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catering_eventos', to='proveedores.proveedor')),
                ('paquete_buffet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='catering.paquetebuffet')),
            ],
            options={
                'verbose_name': 'Catering del evento',
                'verbose_name_plural': 'Catering de eventos',
                'ordering': ['evento', 'hora_servicio'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteBuffetAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_incluida', models.CharField(blank=True, max_length=120, null=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes_buffet', to='catering.alimento')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos_incluidos', to='catering.paquetebuffet')),
            ],
            options={
                'verbose_name': 'Alimento incluido en buffet',
                'verbose_name_plural': 'Alimentos incluidos en buffet',
                'ordering': ['paquete', 'alimento__categoria__nombre', 'alimento__nombre'],
                'unique_together': {('paquete', 'alimento')},
            },
        ),
    ]
