"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Construye rutas en el proyecto. BASE_DIR apunta al directorio raíz del proyecto.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ajustes de seguridad y desarrollo
SECRET_KEY = 'django-insecure-8_3j=5n014qd2j3k+s0dwi5f+5pl_gxuxwcl)x(*+uk$un0ch+'
# Clave secreta para cifrado, sesiones y otros componentes de Django.

DEBUG = True
# Modo de depuración activado: muestra errores detallados y recarga automática.

ALLOWED_HOSTS = []
# Lista de dominios permitidos. En desarrollo se usa vacío; en producción debe configurarse.

# Definición de aplicaciones instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'invitaciones',
]
# Incluye la aplicación personalizada 'invitaciones' junto con apps de Django.

# Middleware: componentes que procesan las solicitudes y respuestas.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'
# Módulo que define las rutas raíz del proyecto.

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# Configuración del motor de plantillas de Django.

WSGI_APPLICATION = 'config.wsgi.application'
# Entrada WSGI para despliegues y servidores de producción.

# Configuración de la base de datos SQLite.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Validación de contraseñas para los usuarios.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internacionalización y configuración de zona horaria.
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Configuración de archivos estáticos.
STATIC_URL = 'static/'
