# Generated by Django 6.0.4 on 2026-07-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaqueteBoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_personas_incluidas', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paquete comercial',
                'verbose_name_plural': 'Paquetes comerciales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_acordado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('servicios_adicionales', models.TextField(blank=True, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('PROPUESTO', 'Propuesto'), ('EN_REVISION', 'En revision'), ('APROBADO', 'Aprobado'), ('CONTRATADO', 'Contratado'), ('CANCELADO', 'Cancelado')], default='PROPUESTO', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetes_evento', to='invitaciones.eventoboda')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='paquetes.paqueteboda')),
            ],
            options={
                'verbose_name': 'Paquete asignado al evento',
                'verbose_name_plural': 'Paquetes asignados a eventos',
                'ordering': ['evento', 'estado', 'paquete__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('SALON', 'Salon'), ('BANQUETE', 'Banquete'), ('MESEROS', 'Meseros'), ('DECORACION', 'Decoracion'), ('MANTELERIA', 'Manteleria'), ('DJ', 'DJ'), ('BANDA', 'Banda'), ('FOTOGRAFIA', 'Fotografia'), ('VIDEO', 'Video'), ('PASTEL', 'Pastel'), ('BARRA_LIBRE', 'Barra libre'), ('INVITACIONES', 'Invitaciones'), ('COORDINACION', 'Coordinacion'), ('MOBILIARIO', 'Mobiliario'), ('ILUMINACION', 'Iluminacion'), ('TRANSPORTE', 'Transporte'), ('OTRO', 'Otro')], max_length=30)),
                ('descripcion', models.CharField(max_length=220)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_incluido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='paquetes.paqueteboda')),
            ],
            options={
                'verbose_name': 'Servicio de paquete',
                'verbose_name_plural': 'Servicios de paquete',
                'ordering': ['paquete', 'tipo_servicio', 'descripcion'],
            },
        ),
    ]
