# Generated by Django 6.0.4 on 2026-08-17 23:03

import catalogo.storage
import django.db.models.deletion
import invitaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_proveedorserviciocatalogo'),
        ('invitaciones', '0033_repair_component_layout_columns'),
        ('organizaciones', '0002_empresasuscriptora_colores_marca_and_more'),
        ('paquetes', '0003_package_snapshot_materialization_k83'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteboda',
            name='capacidad_maxima_recomendada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paqueteboda',
            name='capacidad_minima_recomendada',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paqueteboda',
            name='cargo_fijo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paqueteboda',
            name='duracion_evento',
            field=models.PositiveIntegerField(blank=True, help_text='Duracion comercial en horas.', null=True),
        ),
        migrations.AddField(
            model_name='paqueteboda',
            name='pdf_comercial',
            field=models.FileField(blank=True, null=True, storage=catalogo.storage.PrivateCatalogoStorage(), upload_to='paquetes/pdfs/', validators=[invitaciones.models.validar_documento]),
        ),
        migrations.AddField(
            model_name='paqueteboda',
            name='portada',
            field=models.FileField(blank=True, null=True, storage=catalogo.storage.PrivateCatalogoStorage(), upload_to='paquetes/portadas/', validators=[invitaciones.models.validar_imagen]),
        ),
        migrations.AddField(
            model_name='paqueteboda',
            name='precio_adulto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paqueteboda',
            name='precio_nino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='PropuestaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adultos', models.PositiveIntegerField(default=0)),
                ('ninos', models.PositiveIntegerField(default=0)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROPUESTA', 'Propuesta'), ('EN_REVISION', 'En revision'), ('ACEPTADO', 'Aceptado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20)),
                ('notas_comerciales', models.TextField(blank=True, null=True)),
                ('subtotal_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('version_calculo', models.PositiveIntegerField(default=1)),
                ('desglose_calculado', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_k9_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_k9', to='organizaciones.empresasuscriptora')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_k9', to='invitaciones.eventoboda')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_k9', to='paquetes.paqueteboda')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_k9', to='organizaciones.sedeevento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_k9_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propuesta comercial K9',
                'verbose_name_plural': 'Propuestas comerciales K9',
                'ordering': ['evento', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADICIONAL', 'Adicional'), ('CORTESIA', 'Cortesia')], default='ADICIONAL', max_length=12)),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modo_precio', models.CharField(choices=[('FIJO', 'Fijo'), ('POR_ADULTO', 'Por adulto'), ('POR_NINO', 'Por nino'), ('POR_PERSONA', 'Por persona'), ('POR_UNIDAD', 'Por unidad'), ('MANUAL', 'Manual')], default='FIJO', max_length=20)),
                ('tarifa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_informativo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('snapshot_linea', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('propuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='paquetes.propuestaevento')),
                ('servicio_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lineas_propuesta_k9', to='catalogo.serviciocatalogo')),
            ],
            options={
                'verbose_name': 'Linea de propuesta K9',
                'verbose_name_plural': 'Lineas de propuesta K9',
                'ordering': ['propuesta', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaqueteMediaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IMAGEN', 'Imagen'), ('PDF', 'PDF')], max_length=10)),
                ('archivo', models.FileField(storage=catalogo.storage.PrivateCatalogoStorage(), upload_to='paquetes/media/')),
                ('titulo', models.CharField(blank=True, max_length=140, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_comercial', to='paquetes.paqueteboda')),
            ],
            options={
                'verbose_name': 'Media comercial de paquete',
                'verbose_name_plural': 'Media comercial de paquetes',
                'ordering': ['paquete', 'orden', 'id'],
                'indexes': [models.Index(fields=['paquete', 'tipo'], name='paq_media_pkg_tipo_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaqueteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('incluido', models.BooleanField(default=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('clave_origen', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_catalogo_k9', to='paquetes.paqueteboda')),
                ('servicio_catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes_servicio_k9', to='catalogo.serviciocatalogo')),
            ],
            options={
                'verbose_name': 'Servicio K9 de paquete',
                'verbose_name_plural': 'Servicios K9 de paquete',
                'ordering': ['paquete', 'orden', 'id'],
                'indexes': [models.Index(fields=['paquete', 'incluido'], name='paq_srv_pkg_incl_idx'), models.Index(fields=['servicio_catalogo'], name='paq_srv_catalogo_idx')],
                'constraints': [models.UniqueConstraint(fields=('paquete', 'clave_origen'), name='paquete_servicio_clave_origen_unica')],
            },
        ),
        migrations.AddIndex(
            model_name='propuestaevento',
            index=models.Index(fields=['empresa', 'estado'], name='paq_prop_emp_est_idx'),
        ),
        migrations.AddIndex(
            model_name='propuestaevento',
            index=models.Index(fields=['evento', 'estado'], name='paq_prop_evt_est_idx'),
        ),
        migrations.AddIndex(
            model_name='propuestalinea',
            index=models.Index(fields=['propuesta', 'tipo', 'activo'], name='paq_linea_prop_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='propuestalinea',
            index=models.Index(fields=['servicio_catalogo'], name='paq_linea_catalogo_idx'),
        ),
    ]
