# Generated by Django 6.0.4 on 2026-08-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0004_paqueteboda_capacidad_maxima_recomendada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestaevento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('PROPUESTA', 'Propuesta'), ('EN_REVISION', 'En revision'), ('ACEPTADO', 'Aceptado'), ('CONTRATADO', 'Contratado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20),
        ),
    ]
