export const FONT_OPTIONS = Object.freeze([
    ["Georgia, serif", "Georgia"],
    ["'Times New Roman', serif", "Times New Roman"],
    ["'Cormorant Garamond', serif", "Cormorant Garamond"],
    ["'Playfair Display', serif", "Playfair Display"],
    ["Cinzel, serif", "Cinzel"],
    ["'Libre Baskerville', serif", "Libre Baskerville"],
    ["'Bodoni Moda', serif", "Bodoni Moda"],
    ["'Great Vibes', cursive", "Great Vibes"],
    ["Parisienne, cursive", "Parisienne"],
    ["Allura, cursive", "Allura"],
    ["'Alex Brush', cursive", "Alex Brush"],
    ["Sacramento, cursive", "Sacramento"],
    ["Tangerine, cursive", "Tangerine"],
    ["'Dancing Script', cursive", "Dancing Script"],
    ["Montserrat, sans-serif", "Montserrat"],
    ["Poppins, sans-serif", "Poppins"],
    ["Inter, sans-serif", "Inter"],
    ["Lato, sans-serif", "Lato"],
    ["Raleway, sans-serif", "Raleway"],
    ["'DM Sans', sans-serif", "DM Sans"],
    ["Outfit, sans-serif", "Outfit"],
    ["Manrope, sans-serif", "Manrope"],
    ["Arial, sans-serif", "Arial"],
    ["Verdana, sans-serif", "Verdana"],
    ["'Trebuchet MS', sans-serif", "Trebuchet MS"],
    ["'Courier New', monospace", "Courier New"],
]);
