# Generated by Django 5.2.12 on 2026-07-23 20:34

import django.db.models.deletion
import django.utils.timezone
import invitaciones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('limite_usuarios', models.PositiveIntegerField(default=5)),
                ('limite_wedding_planners', models.PositiveIntegerField(default=3)),
                ('limite_eventos_activos', models.PositiveIntegerField(default=10)),
                ('limite_clientes', models.PositiveIntegerField(default=50)),
                ('limite_almacenamiento_mb', models.PositiveIntegerField(default=1024)),
                ('permite_proveedores', models.BooleanField(default=True)),
                ('permite_reportes', models.BooleanField(default=True)),
                ('permite_api', models.BooleanField(default=False)),
                ('permite_personalizacion', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de suscripcion',
                'verbose_name_plural': 'Planes de suscripcion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_periodo_gracia', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PRUEBA', 'Prueba'), ('ACTIVA', 'Activa'), ('PROXIMA_A_VENCER', 'Proxima a vencer'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='PRUEBA', max_length=25)),
                ('renovacion_automatica', models.BooleanField(default=False)),
                ('bloqueada_manualmente', models.BooleanField(default=False)),
                ('motivo_bloqueo', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='organizaciones.empresasuscriptora')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones', to='suscripciones.plansuscripcion')),
            ],
            options={
                'verbose_name': 'Suscripcion de empresa',
                'verbose_name_plural': 'Suscripciones de empresa',
                'ordering': ['fecha_vencimiento', 'empresa__nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='PagoSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=150)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='suscripciones/comprobantes/', validators=[invitaciones.models.validar_documento])),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_suscripcion', to='organizaciones.empresasuscriptora')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='suscripciones.suscripcionempresa')),
            ],
            options={
                'verbose_name': 'Pago de suscripcion',
                'verbose_name_plural': 'Pagos de suscripcion',
                'ordering': ['-fecha_vencimiento', '-fecha_registro'],
            },
        ),
    ]
