# Generated by Django 6.0.4 on 2026-07-23 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AprobacionEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DECORACION', 'Decoracion'), ('MENU', 'Menu'), ('PROVEEDOR', 'Proveedor'), ('PAQUETE', 'Paquete'), ('PRESUPUESTO', 'Presupuesto'), ('MESAS', 'Distribucion de mesas'), ('ITINERARIO', 'Itinerario'), ('INVITACION', 'Diseno de invitacion'), ('MUSICA', 'Musica'), ('OTRO', 'Otro')], max_length=30)),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CAMBIOS', 'Solicitud de cambios')], default='PENDIENTE', max_length=20)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_respondidas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_evento', to='invitaciones.eventoboda')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobacion del evento',
                'verbose_name_plural': 'Aprobaciones del evento',
                'ordering': ['evento', 'estado', '-fecha_solicitud'],
            },
        ),
    ]
