# Generated by Django 6.0.4 on 2026-07-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('REDONDA', 'Redonda'), ('RECTANGULAR', 'Rectangular'), ('PRINCIPAL', 'Mesa principal'), ('PROTAGONISTAS', 'Mesa de protagonistas'), ('PROVEEDORES', 'Mesa de proveedores'), ('OTRA', 'Otra')], default='REDONDA', max_length=20)),
                ('capacidad', models.PositiveIntegerField(default=10)),
                ('zona', models.CharField(blank=True, max_length=100, null=True)),
                ('posicion_x', models.PositiveIntegerField(default=0)),
                ('posicion_y', models.PositiveIntegerField(default=0)),
                ('ancho', models.PositiveIntegerField(default=140)),
                ('alto', models.PositiveIntegerField(default=140)),
                ('rotacion', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesas_evento', to='invitaciones.eventoboda')),
                ('mesero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_como_mesero', to='proveedores.personalevento')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['evento', 'numero', 'nombre'],
                'unique_together': {('evento', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('grupo_invitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_mesa', to='invitaciones.grupoinvitacion')),
                ('invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_mesa', to='invitaciones.invitado')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='mesas.mesa')),
            ],
            options={
                'verbose_name': 'Asignacion de mesa',
                'verbose_name_plural': 'Asignaciones de mesa',
                'ordering': ['mesa', 'numero_asiento', 'id'],
            },
        ),
    ]
