# Generated by Django 6.0.4 on 2026-07-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=160)),
                ('razon_social', models.CharField(blank=True, max_length=180, null=True)),
                ('tipo_proveedor', models.CharField(choices=[('SALON', 'Salon'), ('JARDIN', 'Jardin'), ('BANQUETE', 'Banquete'), ('BUFFET', 'Buffet'), ('FOTOGRAFIA', 'Fotografia'), ('VIDEO', 'Video'), ('BANDA', 'Banda'), ('DJ', 'DJ'), ('MUSICA_VIVO', 'Musica en vivo'), ('DECORACION', 'Decoracion'), ('FLORERIA', 'Floreria'), ('MANTELERIA', 'Manteleria'), ('MESEROS', 'Meseros'), ('BARRA', 'Barra de bebidas'), ('PASTEL', 'Pastel'), ('TRANSPORTE', 'Transporte'), ('MAQUILLAJE', 'Maquillaje'), ('PEINADO', 'Peinado'), ('VESTUARIO', 'Vestuario'), ('SEGURIDAD', 'Seguridad'), ('ILUMINACION', 'Iluminacion'), ('AUDIO', 'Audio'), ('MOBILIARIO', 'Renta de mobiliario'), ('INVITACIONES', 'Invitaciones'), ('RECUERDOS', 'Recuerdos'), ('OTROS', 'Otros')], default='OTROS', max_length=30)),
                ('nombre_contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('redes_sociales', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('calificacion', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='PersonalEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_personal', models.CharField(choices=[('CAPITAN', 'Capitan de meseros'), ('MESERO', 'Mesero'), ('BARTENDER', 'Bartender'), ('COCINA', 'Personal de cocina'), ('LIMPIEZA', 'Limpieza'), ('SEGURIDAD', 'Seguridad'), ('MONTAJE', 'Montaje'), ('COORDINACION', 'Coordinacion'), ('OTRO', 'Otro')], default='MESERO', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('area_asignada', models.CharField(blank=True, max_length=120, null=True)),
                ('mesas_asignadas', models.CharField(blank=True, max_length=180, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uniforme', models.CharField(blank=True, max_length=180, null=True)),
                ('estado', models.CharField(choices=[('REQUERIDO', 'Requerido'), ('CONFIRMADO', 'Confirmado'), ('EN_SITIO', 'En sitio'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='REQUERIDO', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_evento', to='invitaciones.eventoboda')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_asignado', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Personal del evento',
                'verbose_name_plural': 'Personal del evento',
                'ordering': ['evento', 'tipo_personal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_servicio', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=180, null=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_limite_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('COTIZADO', 'Cotizado'), ('PENDIENTE_APROBACION', 'Pendiente de aprobacion'), ('APROBADO', 'Aprobado'), ('CONTRATADO', 'Contratado'), ('ANTICIPO_PAGADO', 'Anticipo pagado'), ('LIQUIDADO', 'Liquidado'), ('CANCELADO', 'Cancelado'), ('SERVICIO_COMPLETADO', 'Servicio completado')], default='SOLICITADO', max_length=30)),
                ('contrato', models.FileField(blank=True, null=True, upload_to='proveedores/contratos/')),
                ('cotizacion', models.FileField(blank=True, null=True, upload_to='proveedores/cotizaciones/')),
                ('comprobante_pago', models.FileField(blank=True, null=True, upload_to='proveedores/comprobantes/')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_contratados', to='invitaciones.eventoboda')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_evento', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Servicio contratado',
                'verbose_name_plural': 'Servicios contratados',
                'ordering': ['evento', 'fecha_servicio', 'hora_inicio', 'nombre_servicio'],
            },
        ),
    ]
