# Generated by Django 6.0.4 on 2026-07-23 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0001_initial'),
        ('proveedores', '0002_proveedor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='organizaciones.empresasuscriptora'),
        ),
    ]
