# Generated by Django 5.2.12 on 2026-07-23 19:49

import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_proveedor_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioevento',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='proveedores/comprobantes/', validators=[invitaciones.models.validar_documento]),
        ),
        migrations.AlterField(
            model_name='servicioevento',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='proveedores/contratos/', validators=[invitaciones.models.validar_documento]),
        ),
        migrations.AlterField(
            model_name='servicioevento',
            name='cotizacion',
            field=models.FileField(blank=True, null=True, upload_to='proveedores/cotizaciones/', validators=[invitaciones.models.validar_documento]),
        ),
    ]
