# Generated by Django 5.2.12 on 2026-07-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_alter_servicioevento_comprobante_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='contacto_operativo',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='correo_operativo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='datos_bancarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notas_privadas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_operativo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='visible_para_wedding_planners',
            field=models.BooleanField(default=True),
        ),
    ]
