# Generated by Django 6.0.4 on 2026-08-18 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_proveedorserviciocatalogo'),
        ('eventos', '0004_contratoevento_materializacion_version_and_more'),
        ('invitaciones', '0033_repair_component_layout_columns'),
        ('paquetes', '0005_alter_propuestaevento_estado'),
        ('proveedores', '0009_financial_semantics_k831'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioevento',
            name='contrato_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_materializados', to='eventos.contratoevento'),
        ),
        migrations.AddField(
            model_name='servicioevento',
            name='linea_origen_key',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='servicioevento',
            name='materializacion_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='servicioevento',
            name='prestacion_tipo',
            field=models.CharField(choices=[('POR_DEFINIR', 'Por definir'), ('EMPRESA', 'Empresa'), ('PROVEEDOR', 'Proveedor')], default='POR_DEFINIR', max_length=20),
        ),
        migrations.AddField(
            model_name='servicioevento',
            name='servicio_catalogo_k9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_evento_k9', to='catalogo.serviciocatalogo'),
        ),
        migrations.AddField(
            model_name='servicioevento',
            name='snapshot_linea',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='servicioevento',
            name='modalidad',
            field=models.CharField(choices=[('INCLUIDO', 'Incluido en paquete'), ('ADICIONAL', 'Servicio adicional'), ('UPGRADE', 'Upgrade / diferencia'), ('CORTESIA', 'Cortesia')], default='ADICIONAL', max_length=15),
        ),
        migrations.AddIndex(
            model_name='servicioevento',
            index=models.Index(fields=['contrato_origen', 'linea_origen_key'], name='prov_srv_ctr_line_idx'),
        ),
        migrations.AddIndex(
            model_name='servicioevento',
            index=models.Index(fields=['servicio_catalogo_k9'], name='prov_srv_cat_k9_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicioevento',
            constraint=models.UniqueConstraint(fields=('contrato_origen', 'linea_origen_key'), name='prov_srv_contrato_linea_unica'),
        ),
    ]
