# Generated by Django 6.0.4 on 2026-07-23 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0020_grupoinvitacion_alergias_and_more'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoDecoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ARREGLOS', 'Arreglos'), ('FLORES', 'Flores'), ('MANTELES', 'Manteles'), ('SERVILLETAS', 'Servilletas'), ('SILLAS', 'Sillas'), ('MESAS', 'Mesas'), ('CENTROS_MESA', 'Centros de mesa'), ('ILUMINACION', 'Iluminacion'), ('ESCENARIO', 'Escenario'), ('CEREMONIA', 'Ceremonia'), ('RECEPCION', 'Recepcion'), ('MESA_PRINCIPAL', 'Mesa principal'), ('ACCESORIOS', 'Accesorios'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('color', models.CharField(blank=True, max_length=80, null=True)),
                ('material', models.CharField(blank=True, max_length=120, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imagen_referencia', models.FileField(blank=True, null=True, upload_to='decoracion/referencias/')),
                ('imagen_final', models.FileField(blank=True, null=True, upload_to='decoracion/finales/')),
                ('aprobado_cliente', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('IDEA', 'Idea'), ('COTIZADO', 'Cotizado'), ('EN_REVISION', 'En revision'), ('APROBADO', 'Aprobado'), ('COMPRADO', 'Comprado'), ('RENTADO', 'Rentado'), ('LISTO_MONTAJE', 'Listo para montaje'), ('MONTADO', 'Montado'), ('CANCELADO', 'Cancelado')], default='IDEA', max_length=30)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos_decoracion', to='invitaciones.eventoboda')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_decoracion', to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Elemento de decoracion',
                'verbose_name_plural': 'Elementos de decoracion',
                'ordering': ['evento', 'categoria', 'nombre'],
            },
        ),
    ]
