# Generated by Django 5.2.12 on 2026-07-23 19:49

import invitaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementodecoracion',
            name='imagen_final',
            field=models.FileField(blank=True, null=True, upload_to='decoracion/finales/', validators=[invitaciones.models.validar_imagen]),
        ),
        migrations.AlterField(
            model_name='elementodecoracion',
            name='imagen_referencia',
            field=models.FileField(blank=True, null=True, upload_to='decoracion/referencias/', validators=[invitaciones.models.validar_imagen]),
        ),
    ]
